# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'timer_app.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(394, 316)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btnStartPause = QtWidgets.QPushButton(self.centralwidget)
        self.btnStartPause.setGeometry(QtCore.QRect(90, 250, 111, 27))
        self.btnStartPause.setObjectName("btnStartPause")
        self.btnReset = QtWidgets.QPushButton(self.centralwidget)
        self.btnReset.setGeometry(QtCore.QRect(230, 250, 88, 27))
        self.btnReset.setObjectName("btnReset")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(120, 20, 160, 80))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lcdNumber = QtWidgets.QLCDNumber(self.verticalLayoutWidget)
        self.lcdNumber.setObjectName("lcdNumber")
        self.verticalLayout.addWidget(self.lcdNumber)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(90, 140, 226, 83))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.comboMode = QtWidgets.QComboBox(self.verticalLayoutWidget_2)
        self.comboMode.setObjectName("comboMode")
        self.comboMode.addItem("")
        self.comboMode.addItem("")
        self.verticalLayout_2.addWidget(self.comboMode)
        self.lineEditTime = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEditTime.setObjectName("lineEditTime")
        self.verticalLayout_2.addWidget(self.lineEditTime)
        self.labelHint = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.labelHint.setObjectName("labelHint")
        self.verticalLayout_2.addWidget(self.labelHint)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btnStartPause.setText(_translate("MainWindow", "Старт/Cтоп"))
        self.btnReset.setText(_translate("MainWindow", "Сброс"))
        self.comboMode.setItemText(0, _translate("MainWindow", "Секундомер"))
        self.comboMode.setItemText(1, _translate("MainWindow", "Таймер"))
        self.labelHint.setText(_translate("MainWindow", "Формат ММ:СС или ЧЧ:ММ:СС"))
